export const categories = [
    {
        categoryName: "For Women",
        categoryLink: "shop-grid-ls.html",
        categoryLinkName:"Shop for women",
        categoryImage: "assets/img/home/categories/cat-lg02.jpg",
        categoryImageAlt: "Category image",
        categoryProducts: [
            {
                productId:"200",
                productLink: "/shop/Cosmetics/200",
                productImage: "assets/img/shop/catalog/09.jpg",
                productImageAlt: "Product image",
                productCategory: "Cosmetics",
                productTitle: "Metallic Lipstick (Crimson)",
                productPrice: "12.99",
                productOldPrice: "18.99",
                productRating: 4,
            },
            {
                productId:"301",
                productLink: "shop-single-v1.html",
                productImage: "assets/img/shop/catalog/27.jpg",
                productImageAlt: "Product image",
                productCategory: "Shoes",
                productTitle: "Textile Platform Sneakers",
                productPrice: "59.99",
                productRating: 5,
            },
            {
                productId:"302",
                productLink: "shop-single-v1.html",
                productImage: "assets/img/shop/catalog/27.jpg",
                productImageAlt: "Product image",
                productCategory: "Accessories",
                productTitle: "Polarized Sunglasses",
                productPrice: "17.99",
                productOldPrice: "28.99",
                productRating: 3,
            },
            {
                productId:"303",
                productLink: "shop-single-v1.html",
                productImage: "assets/img/shop/catalog/28.jpg",
                productImageAlt: "Product image",
                productCategory: "Shoes",
                productTitle: "Leather Platform Sandals",
                productPrice: "79.99",
                productRating: 5,
            },
            {
                productId:"304",
                productLink: "shop-single-v1.html",
                productImage: "assets/img/shop/catalog/29.jpg",
                productImageAlt: "Product image",
                productCategory: "Shorts",
                productTitle: "Short Chino Shorts",
                productPrice: "24.99",
                productRating: 4,
            },
            {
                productId:"305",
                productLink: "shop-single-v1.html",
                productImage: "assets/img/shop/catalog/29.jpg",
                productImageAlt: "Product image",
                productCategory: "T-shirts",
                productTitle: "T-shirt with Motif",
                productPrice: "13.99",
                productRating: 4,
            },
            {
                productId:"306",
                productLink: "shop-single-v1.html",
                productImage: "assets/img/shop/catalog/01.jpg",
                productImageAlt: "Product image",
                productCategory: "Shoes",
                productTitle: "Colorblock Sneakers",
                productPrice: "154.99",
                productRating: 4,
            },
            {
                productId:"307",
                productLink: "shop-single-v1.html",
                productImage: "assets/img/shop/catalog/02.jpg",
                productImageAlt: "Product image",
                productCategory: "Blouse",
                productTitle: "Cotton Lave Blouse",
                productPrice: "37.99",
                productRating: 3,
            },
            {
                productId:"308",
                productLink: "shop-single-v1.html",
                productImage: "assets/img/shop/catalog/03.jpg",
                productImageAlt: "Product image",
                productCategory: "Shorts",
                productTitle: "Mom High Waist Shorts",
                productPrice: "39.50",
                productRating: 5,
            },
            {
                productId:"309",
                productLink: "shop-single-v1.html",
                productImage: "assets/img/shop/catalog/04.jpg",
                productImageAlt: "Product image",
                productCategory: "Sportswear",
                productTitle: "Sports Jacket",
                productPrice: "68.40",
                productRating: 4,
            },
            {
                productId:"310",
                productLink: "shop-single-v1.html",
                productImage: "assets/img/shop/catalog/32.jpg",
                productImageAlt: "Product image",
                productCategory: "Shorts",
                productTitle: "Leather Platform Sandals",
                productPrice: "67.95",
                productRating: 3,
            },
            {
                productId:"311",
                productLink: "/shop",
                productImage: "assets/img/shop/catalog/07.jpg",
                productImageAlt: "Product image",
                productCategory: "T-shirts",
                productTitle: "Two-Piece Bikini",
                productPrice: "18.99",
                productRating: 4,
            },
            
        ]
    },
    {
        categoryName: "For Men",
        categoryLink: "shop-grid-ls.html",
        categoryLinkName:"Shop for men",
        categoryImage: "assets/img/home/categories/cat-lg01.jpg",
        categoryImageAlt: "Category image",
        categoryProducts: [
            {
                productId:"400",
                productLink: "shop-single-v1.html",
                productImage: "assets/img/shop/catalog/32.jpg",
                productImageAlt: "Product image",
                productCategory: "Hats & Caps",
                productTitle: "Cap with Appliqué",
                productPrice: "15.99",
                productRating: 5,
            },
            {
                productId:"401",
                productLink: "shop-single-v1.html",
                productImage: "assets/img/shop/catalog/33.jpg",
                productImageAlt: "Product image",
                productCategory: "T-shirts",
                productTitle: "Regular Fit Cotton Shirt",
                productPrice: "19.99",
                productRating: 5,
            },
            {
                productId:"402",
                productLink: "shop-single-v1.html",
                productImage: "assets/img/shop/catalog/34.jpg",
                productImageAlt: "Product image",
                productCategory: "Accessories",
                productTitle: "Polarized Sunglasses",
                productPrice: "37.99",
                productRating: 4,
            },
            {
                productId:"403",
                productLink: "shop-single-v1.html",
                productImage: "assets/img/shop/catalog/35.jpg",
                productImageAlt: "Product image",
                productCategory: "Shoes",
                productTitle: "Leather Men’s Sneakers",
                productPrice: "45.99",
                productRating: 4,
            },
            {
                productId:"404",
                productLink: "shop-single-v1.html",
                productImage: "assets/img/shop/catalog/29.jpg",
                productImageAlt: "Product image",
                productCategory: "Shorts",
                productTitle: "Short Chino Shorts",
                productPrice: "24.99",
                productRating: 4,
            },
            {
                productId:"405",
                productLink: "shop-single-v1.html",
                productImage: "assets/img/shop/catalog/29.jpg",
                productImageAlt: "Product image",
                productCategory: "T-shirts",
                productTitle: "T-shirt with Motif",
                productPrice: "13.99",
                productRating: 4,
            },
            {
                productId:"406",
                productLink: "shop-single-v1.html",
                productImage: "assets/img/shop/catalog/01.jpg",
                productImageAlt: "Product image",
                productCategory: "Shoes",
                productTitle: "Colorblock Sneakers",
                productPrice: "154.99",
                productRating: 4,
            },
            {
                productId:"407",
                productLink: "shop-single-v1.html",
                productImage: "assets/img/shop/catalog/02.jpg",
                productImageAlt: "Product image",
                productCategory: "Blouse",
                productTitle: "Cotton Lave Blouse",
                productPrice: "37.99",
                productRating: 3,
            },
            {
                productId:"408",
                productLink: "shop-single-v1.html",
                productImage: "assets/img/shop/catalog/03.jpg",
                productImageAlt: "Product image",
                productCategory: "Shorts",
                productTitle: "Mom High Waist Shorts",
                productPrice: "39.50",
                productRating: 5,
            },
            {
                productId:"409",
                productLink: "shop-single-v1.html",
                productImage: "assets/img/shop/catalog/04.jpg",
                productImageAlt: "Product image",
                productCategory: "Sportswear",
                productTitle: "Sports Jacket",
                productPrice: "68.40",
                productRating: 4,
            },
            {
                productId:"410",
                productLink: "shop-single-v1.html",
                productImage: "assets/img/shop/catalog/32.jpg",
                productImageAlt: "Product image",
                productCategory: "Shorts",
                productTitle: "Leather Platform Sandals",
                productPrice: "67.95",
                productRating: 3,
            },
            {
                productId:"411",
                productLink: "shop-single-v1.html",
                productImage: "assets/img/shop/catalog/07.jpg",
                productImageAlt: "Product image",
                productCategory: "T-shirts",
                productTitle: "Two-Piece Bikini",
                productPrice: "18.99",
                productRating: 4,
            },
            
        ]
    },
    {
        categoryName: "For Kids",
        categoryLink: "shop-grid-ls.html",
        categoryLinkName:"Shop for kids",
        categoryImage: "assets/img/home/categories/cat-lg03.jpg",
        categoryImageAlt: "Category image",
        categoryProducts: [
            {
                productId:"500",
                productLink: "shop-single-v1.html",
                productImage: "assets/img/shop/catalog/09.jpg",
                productImageAlt: "Product image",
                productCategory: "Cosmetics",
                productTitle: "Metallic Lipstick (Crimson)",
                productPrice: "12.99",
                productOldPrice: "18.99",
                productRating: 4,
            },
            {
                productId:"501",
                productLink: "shop-single-v1.html",
                productImage: "assets/img/shop/catalog/27.jpg",
                productImageAlt: "Product image",
                productCategory: "Shoes",
                productTitle: "Textile Platform Sneakers",
                productPrice: "59.99",
                productRating: 5,
            },
            {
                productId:"502",
                productLink: "shop-single-v1.html",
                productImage: "assets/img/shop/catalog/27.jpg",
                productImageAlt: "Product image",
                productCategory: "Accessories",
                productTitle: "Polarized Sunglasses",
                productPrice: "17.99",
                productOldPrice: "28.99",
                productRating: 3,
            },
            {
                productId:"503",
                productLink: "shop-single-v1.html",
                productImage: "assets/img/shop/catalog/28.jpg",
                productImageAlt: "Product image",
                productCategory: "Shoes",
                productTitle: "Leather Platform Sandals",
                productPrice: "79.99",
                productRating: 5,
            },
            {
                productId:"504",
                productLink: "shop-single-v1.html",
                productImage: "assets/img/shop/catalog/29.jpg",
                productImageAlt: "Product image",
                productCategory: "Shorts",
                productTitle: "Short Chino Shorts",
                productPrice: "24.99",
                productRating: 4,
            },
            {
                productId:"505",
                productLink: "shop-single-v1.html",
                productImage: "assets/img/shop/catalog/29.jpg",
                productImageAlt: "Product image",
                productCategory: "T-shirts",
                productTitle: "T-shirt with Motif",
                productPrice: "13.99",
                productRating: 4,
            },
            {
                productId:"506",
                productLink: "shop-single-v1.html",
                productImage: "assets/img/shop/catalog/01.jpg",
                productImageAlt: "Product image",
                productCategory: "Shoes",
                productTitle: "Colorblock Sneakers",
                productPrice: "154.99",
                productRating: 4,
            },
            {
                productId:"507",
                productLink: "shop-single-v1.html",
                productImage: "assets/img/shop/catalog/02.jpg",
                productImageAlt: "Product image",
                productCategory: "Blouse",
                productTitle: "Cotton Lave Blouse",
                productPrice: "37.99",
                productRating: 3,
            },
            {
                productId:"508",
                productLink: "shop-single-v1.html",
                productImage: "assets/img/shop/catalog/03.jpg",
                productImageAlt: "Product image",
                productCategory: "Shorts",
                productTitle: "Mom High Waist Shorts",
                productPrice: "39.50",
                productRating: 5,
            },
            {
                productId:"509",
                productLink: "shop-single-v1.html",
                productImage: "assets/img/shop/catalog/04.jpg",
                productImageAlt: "Product image",
                productCategory: "Sportswear",
                productTitle: "Sports Jacket",
                productPrice: "68.40",
                productRating: 4,
            },
            {
                productId:"510",
                productLink: "shop-single-v1.html",
                productImage: "assets/img/shop/catalog/32.jpg",
                productImageAlt: "Product image",
                productCategory: "Shorts",
                productTitle: "Leather Platform Sandals",
                productPrice: "67.95",
                productRating: 3,
            },
            {
                productId:"511",
                productLink: "shop-single-v1.html",
                productImage: "assets/img/shop/catalog/07.jpg",
                productImageAlt: "Product image",
                productCategory: "T-shirts",
                productTitle: "Two-Piece Bikini",
                productPrice: "18.99",
                productRating: 4,
            },
            
        ]
    },
]