export const categories = [
    {
        categoryName: "For Women",
        categoryLink: "shop-grid-ls.html",
        categoryLinkName:"Shop for women",
        categoryImage: "assets/img/home/categories/cat-lg02.jpg",
        categoryImageAlt: "Category image",
        categoryProducts: [
            {
                productId:"200",
                productLink: "/shop",
                productImage: "assets/img/shop/catalog/09.jpg",
                productImageAlt: "Product image",
                productCategory: "Cosmetics",
                productTitle: "Metallic Lipstick (Crimson)",
                productPrice: "12.99",
                productOldPrice: "18.99",
                productRating: 4,
            },
            {
                productId:"201",
                productLink: "shop-single-v1.html",
                productImage: "assets/img/shop/catalog/27.jpg",
                productImageAlt: "Product image",
                productCategory: "Shoes",
                productTitle: "Textile Platform Sneakers",
                productPrice: "59.99",
                productRating: 5,
            },
            {
                productId:"202",
                productLink: "shop-single-v1.html",
                productImage: "assets/img/shop/catalog/27.jpg",
                productImageAlt: "Product image",
                productCategory: "Accessories",
                productTitle: "Polarized Sunglasses",
                productPrice: "17.99",
                productOldPrice: "28.99",
                productRating: 3,
            },
            {
                productId:"203",
                productLink: "shop-single-v1.html",
                productImage: "assets/img/shop/catalog/28.jpg",
                productImageAlt: "Product image",
                productCategory: "Shoes",
                productTitle: "Leather Platform Sandals",
                productPrice: "79.99",
                productRating: 5,
            },
            {
                productId:"204",
                productLink: "shop-single-v1.html",
                productImage: "assets/img/shop/catalog/29.jpg",
                productImageAlt: "Product image",
                productCategory: "Shorts",
                productTitle: "Short Chino Shorts",
                productPrice: "24.99",
                productRating: 4,
            },
            {
                productId:"205",
                productLink: "shop-single-v1.html",
                productImage: "assets/img/shop/catalog/29.jpg",
                productImageAlt: "Product image",
                productCategory: "T-shirts",
                productTitle: "T-shirt with Motif",
                productPrice: "13.99",
                productRating: 4,
            },
            {
                productId:"206",
                productLink: "shop-single-v1.html",
                productImage: "assets/img/shop/catalog/01.jpg",
                productImageAlt: "Product image",
                productCategory: "Shoes",
                productTitle: "Colorblock Sneakers",
                productPrice: "154.99",
                productRating: 4,
            },
            {
                productId:"207",
                productLink: "shop-single-v1.html",
                productImage: "assets/img/shop/catalog/02.jpg",
                productImageAlt: "Product image",
                productCategory: "Blouse",
                productTitle: "Cotton Lave Blouse",
                productPrice: "37.99",
                productRating: 3,
            },
            {
                productId:"208",
                productLink: "shop-single-v1.html",
                productImage: "assets/img/shop/catalog/03.jpg",
                productImageAlt: "Product image",
                productCategory: "Shorts",
                productTitle: "Mom High Waist Shorts",
                productPrice: "39.50",
                productRating: 5,
            },
            {
                productId:"209",
                productLink: "shop-single-v1.html",
                productImage: "assets/img/shop/catalog/04.jpg",
                productImageAlt: "Product image",
                productCategory: "Sportswear",
                productTitle: "Sports Jacket",
                productPrice: "68.40",
                productRating: 4,
            },
            {
                productId:"210",
                productLink: "shop-single-v1.html",
                productImage: "assets/img/shop/catalog/32.jpg",
                productImageAlt: "Product image",
                productCategory: "Shorts",
                productTitle: "Leather Platform Sandals",
                productPrice: "67.95",
                productRating: 3,
            },
            {
                productId:"211",
                productLink: "/shop",
                productImage: "assets/img/shop/catalog/07.jpg",
                productImageAlt: "Product image",
                productCategory: "T-shirts",
                productTitle: "Two-Piece Bikini",
                productPrice: "18.99",
                productRating: 4,
            },
            
        ]
    },
    {
        categoryName: "For Men",
        categoryLink: "shop-grid-ls.html",
        categoryLinkName:"Shop for men",
        categoryImage: "assets/img/home/categories/cat-lg01.jpg",
        categoryImageAlt: "Category image",
        categoryProducts: [
            {
                productId:"200",
                productLink: "shop-single-v1.html",
                productImage: "assets/img/shop/catalog/32.jpg",
                productImageAlt: "Product image",
                productCategory: "Hats & Caps",
                productTitle: "Cap with Appliqué",
                productPrice: "15.99",
                productRating: 5,
            },
            {
                productId:"201",
                productLink: "shop-single-v1.html",
                productImage: "assets/img/shop/catalog/33.jpg",
                productImageAlt: "Product image",
                productCategory: "T-shirts",
                productTitle: "Regular Fit Cotton Shirt",
                productPrice: "19.99",
                productRating: 5,
            },
            {
                productId:"202",
                productLink: "shop-single-v1.html",
                productImage: "assets/img/shop/catalog/34.jpg",
                productImageAlt: "Product image",
                productCategory: "Accessories",
                productTitle: "Polarized Sunglasses",
                productPrice: "37.99",
                productRating: 4,
            },
            {
                productId:"203",
                productLink: "shop-single-v1.html",
                productImage: "assets/img/shop/catalog/35.jpg",
                productImageAlt: "Product image",
                productCategory: "Shoes",
                productTitle: "Leather Men’s Sneakers",
                productPrice: "45.99",
                productRating: 4,
            },
            {
                productId:"204",
                productLink: "shop-single-v1.html",
                productImage: "assets/img/shop/catalog/29.jpg",
                productImageAlt: "Product image",
                productCategory: "Shorts",
                productTitle: "Short Chino Shorts",
                productPrice: "24.99",
                productRating: 4,
            },
            {
                productId:"205",
                productLink: "shop-single-v1.html",
                productImage: "assets/img/shop/catalog/29.jpg",
                productImageAlt: "Product image",
                productCategory: "T-shirts",
                productTitle: "T-shirt with Motif",
                productPrice: "13.99",
                productRating: 4,
            },
            {
                productId:"206",
                productLink: "shop-single-v1.html",
                productImage: "assets/img/shop/catalog/01.jpg",
                productImageAlt: "Product image",
                productCategory: "Shoes",
                productTitle: "Colorblock Sneakers",
                productPrice: "154.99",
                productRating: 4,
            },
            {
                productId:"207",
                productLink: "shop-single-v1.html",
                productImage: "assets/img/shop/catalog/02.jpg",
                productImageAlt: "Product image",
                productCategory: "Blouse",
                productTitle: "Cotton Lave Blouse",
                productPrice: "37.99",
                productRating: 3,
            },
            {
                productId:"208",
                productLink: "shop-single-v1.html",
                productImage: "assets/img/shop/catalog/03.jpg",
                productImageAlt: "Product image",
                productCategory: "Shorts",
                productTitle: "Mom High Waist Shorts",
                productPrice: "39.50",
                productRating: 5,
            },
            {
                productId:"209",
                productLink: "shop-single-v1.html",
                productImage: "assets/img/shop/catalog/04.jpg",
                productImageAlt: "Product image",
                productCategory: "Sportswear",
                productTitle: "Sports Jacket",
                productPrice: "68.40",
                productRating: 4,
            },
            {
                productId:"210",
                productLink: "shop-single-v1.html",
                productImage: "assets/img/shop/catalog/32.jpg",
                productImageAlt: "Product image",
                productCategory: "Shorts",
                productTitle: "Leather Platform Sandals",
                productPrice: "67.95",
                productRating: 3,
            },
            {
                productId:"211",
                productLink: "shop-single-v1.html",
                productImage: "assets/img/shop/catalog/07.jpg",
                productImageAlt: "Product image",
                productCategory: "T-shirts",
                productTitle: "Two-Piece Bikini",
                productPrice: "18.99",
                productRating: 4,
            },
            
        ]
    },
    {
        categoryName: "For Kids",
        categoryLink: "shop-grid-ls.html",
        categoryLinkName:"Shop for kids",
        categoryImage: "assets/img/home/categories/cat-lg03.jpg",
        categoryImageAlt: "Category image",
        categoryProducts: [
            {
                productId:"200",
                productLink: "shop-single-v1.html",
                productImage: "assets/img/shop/catalog/09.jpg",
                productImageAlt: "Product image",
                productCategory: "Cosmetics",
                productTitle: "Metallic Lipstick (Crimson)",
                productPrice: "12.99",
                productOldPrice: "18.99",
                productRating: 4,
            },
            {
                productId:"201",
                productLink: "shop-single-v1.html",
                productImage: "assets/img/shop/catalog/27.jpg",
                productImageAlt: "Product image",
                productCategory: "Shoes",
                productTitle: "Textile Platform Sneakers",
                productPrice: "59.99",
                productRating: 5,
            },
            {
                productId:"202",
                productLink: "shop-single-v1.html",
                productImage: "assets/img/shop/catalog/27.jpg",
                productImageAlt: "Product image",
                productCategory: "Accessories",
                productTitle: "Polarized Sunglasses",
                productPrice: "17.99",
                productOldPrice: "28.99",
                productRating: 3,
            },
            {
                productId:"203",
                productLink: "shop-single-v1.html",
                productImage: "assets/img/shop/catalog/28.jpg",
                productImageAlt: "Product image",
                productCategory: "Shoes",
                productTitle: "Leather Platform Sandals",
                productPrice: "79.99",
                productRating: 5,
            },
            {
                productId:"204",
                productLink: "shop-single-v1.html",
                productImage: "assets/img/shop/catalog/29.jpg",
                productImageAlt: "Product image",
                productCategory: "Shorts",
                productTitle: "Short Chino Shorts",
                productPrice: "24.99",
                productRating: 4,
            },
            {
                productId:"205",
                productLink: "shop-single-v1.html",
                productImage: "assets/img/shop/catalog/29.jpg",
                productImageAlt: "Product image",
                productCategory: "T-shirts",
                productTitle: "T-shirt with Motif",
                productPrice: "13.99",
                productRating: 4,
            },
            {
                productId:"206",
                productLink: "shop-single-v1.html",
                productImage: "assets/img/shop/catalog/01.jpg",
                productImageAlt: "Product image",
                productCategory: "Shoes",
                productTitle: "Colorblock Sneakers",
                productPrice: "154.99",
                productRating: 4,
            },
            {
                productId:"207",
                productLink: "shop-single-v1.html",
                productImage: "assets/img/shop/catalog/02.jpg",
                productImageAlt: "Product image",
                productCategory: "Blouse",
                productTitle: "Cotton Lave Blouse",
                productPrice: "37.99",
                productRating: 3,
            },
            {
                productId:"208",
                productLink: "shop-single-v1.html",
                productImage: "assets/img/shop/catalog/03.jpg",
                productImageAlt: "Product image",
                productCategory: "Shorts",
                productTitle: "Mom High Waist Shorts",
                productPrice: "39.50",
                productRating: 5,
            },
            {
                productId:"209",
                productLink: "shop-single-v1.html",
                productImage: "assets/img/shop/catalog/04.jpg",
                productImageAlt: "Product image",
                productCategory: "Sportswear",
                productTitle: "Sports Jacket",
                productPrice: "68.40",
                productRating: 4,
            },
            {
                productId:"210",
                productLink: "shop-single-v1.html",
                productImage: "assets/img/shop/catalog/32.jpg",
                productImageAlt: "Product image",
                productCategory: "Shorts",
                productTitle: "Leather Platform Sandals",
                productPrice: "67.95",
                productRating: 3,
            },
            {
                productId:"211",
                productLink: "shop-single-v1.html",
                productImage: "assets/img/shop/catalog/07.jpg",
                productImageAlt: "Product image",
                productCategory: "T-shirts",
                productTitle: "Two-Piece Bikini",
                productPrice: "18.99",
                productRating: 4,
            },
            
        ]
    },
]